import { BriefingQuestion } from "@/types";

export const BRIEFING_QUESTIONS: BriefingQuestion[] = [
  {
    id: "brand_name",
    category: "Identidade",
    question: "Qual o nome da marca?",
    type: "text",
    required: true,
  },
  {
    id: "brand_slogan",
    category: "Identidade",
    question: "A marca possui um slogan ou tagline? Se sim, qual?",
    type: "text",
    required: false,
  },
  {
    id: "brand_history",
    category: "Identidade",
    question: "Conte brevemente a historia da marca. Como e por que ela surgiu?",
    type: "textarea",
    required: true,
  },
  {
    id: "brand_mission",
    category: "Identidade",
    question: "Qual a missao da marca? O que ela busca entregar ao mundo?",
    type: "textarea",
    required: true,
  },
  {
    id: "brand_values",
    category: "Identidade",
    question: "Quais sao os valores fundamentais da marca? (Selecione ate 5)",
    type: "multi-select",
    options: [
      "Inovacao", "Tradicao", "Sustentabilidade", "Qualidade",
      "Acessibilidade", "Exclusividade", "Transparencia", "Criatividade",
      "Confianca", "Ousadia", "Simplicidade", "Sofisticacao",
      "Autenticidade", "Comunidade", "Performance",
    ],
    required: true,
  },
  {
    id: "target_audience",
    category: "Publico",
    question: "Quem e o publico-alvo da marca? Descreva o perfil ideal do cliente.",
    type: "textarea",
    required: true,
  },
  {
    id: "target_age",
    category: "Publico",
    question: "Qual a faixa etaria principal do publico?",
    type: "select",
    options: [
      "18-24 anos", "25-34 anos", "35-44 anos",
      "45-54 anos", "55+ anos", "Todas as idades",
    ],
    required: true,
  },
  {
    id: "target_class",
    category: "Publico",
    question: "Qual a classe social predominante do publico?",
    type: "select",
    options: ["A", "B", "C", "D/E", "Todas"],
    required: true,
  },
  {
    id: "brand_personality",
    category: "Personalidade",
    question: "Se a marca fosse uma pessoa, como ela se comportaria? Descreva sua personalidade.",
    type: "textarea",
    required: true,
  },
  {
    id: "brand_tone",
    category: "Personalidade",
    question: "Qual o tom de voz da marca?",
    type: "multi-select",
    options: [
      "Formal", "Informal", "Divertido", "Serio",
      "Inspirador", "Tecnico", "Acolhedor", "Provocativo",
      "Elegante", "Jovem", "Autoritario", "Amigavel",
    ],
    required: true,
  },
  {
    id: "brand_adjectives",
    category: "Personalidade",
    question: "Escolha 3 adjetivos que melhor representam a marca.",
    type: "multi-select",
    options: [
      "Moderna", "Classica", "Minimalista", "Exuberante",
      "Tecnologica", "Artesanal", "Luxuosa", "Popular",
      "Disruptiva", "Confiavel", "Vibrante", "Serena",
      "Robusta", "Delicada", "Urbana", "Natural",
    ],
    required: true,
  },
  {
    id: "competitors",
    category: "Mercado",
    question: "Quais sao os principais concorrentes da marca? (Liste nomes separados por virgula)",
    type: "textarea",
    required: true,
  },
  {
    id: "differentiator",
    category: "Mercado",
    question: "O que diferencia a marca dos concorrentes?",
    type: "textarea",
    required: true,
  },
  {
    id: "color_preferences",
    category: "Visual",
    question: "Existe alguma preferencia de cores para a identidade visual?",
    type: "textarea",
    required: false,
  },
  {
    id: "visual_references",
    category: "Visual",
    question: "Existe alguma marca ou estilo visual que voce admira e gostaria de usar como referencia?",
    type: "textarea",
    required: false,
  },
  {
    id: "avoid",
    category: "Visual",
    question: "Existe algo que a marca definitivamente NAO quer transmitir?",
    type: "textarea",
    required: false,
  },
];
